theme: jekyll-theme-architect
title: Semantic Data Dictionary Resources
description: Here you can find documetation, modelling guidelines, and tutorials for building your own Semantic Data Dictionaries!

permalink: /:title

baseurl: "/sdd"

sass: 
  style: compressed

highlighter: rouge
markdown: kramdown

# Tracker
analytics: UA-133292887-1

# Comments
# disqus-shortname:

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


exclude:
- README.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

